### ISSUE TITLE
Urdu Language Keyboard Issue

### ISSUE THREAD

**Issue by Rafay-kz** [kamran8545/artistic_multilingual_keyboards#1]
On typing Urdu joining letter, cursor is not moving to the end of letter, and double tap on spacebar cursor is moving to the initial position.

**Comment by kamran8545** [comment]
@Rafay-kz Thank you for giving time on finding bugs and reporting them. your mentioned bugs has been resolved and package has been updated on pub.dev you can check out updated version now on pub.dev.
