### ISSUE TITLE
Issue in property keyTextStyle

### ISSUE THREAD

**Issue by afaqueali97** [kamran8545/artistic_multilingual_keyboards#2]
I wanted to increase font size so I tried to use the parameter keyTextStyle. 

I wrote the code mentioned below.
keyTextStyle: const TextStyle(fontSize: 20).

After running the code the keyboard vanished and nothing was visible.

![image](https://user-images.githubusercontent.com/98380148/191027013-2750f112-571c-4a08-88ae-b8fce1e67b7b.png)

**Comment by kamran8545** [comment]
@afaqueali97 thank you for reporting this issue. 

but it is not a bug and the keyboard is not vanishing. what happening is the background color of the keyboard and keys is white, when you are setting the TextStyle property keys text color is getting white as well. so it's looking like the keyboard is vanished but it's there. Change the text color so the text on keys appears.

**Comment by afaqueali97** [comment]
Noted!!
