### ISSUE TITLE
issue in Urdu and Sindhi keyboard

### ISSUE THREAD

**Issue by rafisial5** [kamran8545/artistic_multilingual_keyboards#3]
while writing urdu and sindhi language with special characters and number, 
- Position of cursor is not at accurate place.
- While writing urdu and sindhi language with special characters like $,*,@ etc they are added at first place, then type number 123 at same textfield newly added text move to end.
- On press "123" key, it must show English, Urdu or Sindhi alphabet keyboard .
- "123" should be replaced with "?123".

**Comment by kamran8545** [comment]
@rafisial5 Thank you for your time on testing bugs and reporting them. Your mentioned bugs are resolved and package has been update on pub.dev, you can use now updated version.
